sudo: false
dist: trusty

branches:
  only: master

language: java
jdk: openjdk11

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

matrix:
  include:
    - language: java
      jdk: oraclejdk8
      script:
        - mvn clean install -Dtest=*Test test
      before_script:
        - cd ./backend/

    - language: node_js
      node_js: stable
      install:
        - npm install
      before_install:
        - cd ./frontend/
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      script:
        - npm run build
        - npm run e2e

cache:
  directories:
    - $HOME/.m2